<center>
<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/module_1/images/SN_web_lightmode.png" width="300"> 
</center>

# Assignment: Exploratory Data Analysis with SQL
Estimated time needed: 60 minutes


# Introduction
Using this R notebook you will perform exploratory data analysis using SQL queries with the RSQLite R package. You will be graded on the accuracy of your results as well as the content of your SQL queries.

### Establish your SQL Lite connection

#### Install RSQLite package
The RSQlite  package needs to be installed in your notebook. Let’s load the RSQLite package by clicking on the following cell and executing it (Shift+Enter):

In [1]:
install.packages("https://cran.r-project.org/src/contrib/Archive/RSQLite/RSQLite_0.10.0.tar.gz", repos = NULL, type = "source", dependencies = TRUE)

Warning message in install.packages("https://cran.r-project.org/src/contrib/Archive/RSQLite/RSQLite_0.10.0.tar.gz", :
“installation of package ‘/tmp/RtmpqA3mlj/downloaded_packages/RSQLite_0.10.0.tar.gz’ had non-zero exit status”

#### Restart Kernel

After installing the RSQLite package, it is necessary to restart R Kernel. Click **Kernel** > **Restart Kernel** from the main menu. This will register the newly installed packages. Now proceed to load the RSQLite package.

#### Load RSQLite
Load the 'RSQLite' library, and use the 'dbConnect( )' function as you did in the previous labs to establish the connection to your SQLite database.  
You are now ready to start running SQL queries using the RSQLite library as you did in Course 3.

In [2]:
library("RSQLite")

In [3]:
# provide your solution here to connect db
# Establish an in-memory database connection
conn <- dbConnect(RSQLite::SQLite(), ":memory:")

# Read the datasets from the provided URLs
seoul_bike_sharing <- read.csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/seoul_bike_sharing.csv")
cities_weather_forecast <- read.csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/cities_weather_forecast.csv")
bike_sharing_systems <- read.csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/bike_sharing_systems.csv")
world_cities <- read.csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/world_cities.csv")

# Write the data into SQLite tables
dbWriteTable(conn, "SEOUL_BIKE_SHARING", seoul_bike_sharing)
dbWriteTable(conn, "CITIES_WEATHER_FORECAST", cities_weather_forecast)
dbWriteTable(conn, "BIKE_SHARING_SYSTEMS", bike_sharing_systems)
dbWriteTable(conn, "WORLD_CITIES", world_cities)

Download the following csv files:

*   [WORLD_CITIES](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/world_cities.csv)

*   [BIKE_SHARING_SYSTEMS](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/bike_sharing_systems.csv)

*   [CITIES_WEATHER_FORECAST](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/cities_weather_forecast.csv)

*   [SEOUL_BIKE_SHARING](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/seoul_bike_sharing.csv)

and load the csv's  into 4 tables as mentioned below
* SEOUL_BIKE_SHARING

* CITIES_WEATHER_FORECAST

* BIKE_SHARING_SYSTEMS 

*  WORLD_CITIES

> Hint : Use the read_csv() function and dbWriteTable() functions


## Task 1 - Record Count
#### Determine how many records are in the seoul_bike_sharing dataset.

### Solution 1

In [4]:
# provide your solution here
dbGetQuery(conn, "
    SELECT COUNT(*) AS TOTAL_RECORDS 
    FROM SEOUL_BIKE_SHARING
")

  TOTAL_RECORDS
1 8465

## Task 2 - Operational Hours
#### Determine how many hours had non-zero rented bike count.

### Solution 2

In [5]:
# provide your solution here
dbGetQuery(conn, "
    SELECT COUNT(HOUR) AS NON_ZERO_HOURS 
    FROM SEOUL_BIKE_SHARING 
    WHERE RENTED_BIKE_COUNT > 0
")

  NON_ZERO_HOURS
1 8465

## Task 3 - Weather Outlook
#### Query the the weather forecast for Seoul over the next 3 hours.
Recall that the records in the CITIES_WEATHER_FORECAST dataset are 3 hours apart, so we just need the first record from the query.

### Solution 3

In [6]:
# provide your solution here
dbGetQuery(conn, "
    SELECT * FROM CITIES_WEATHER_FORECAST 
    WHERE CITY = 'Seoul' 
    LIMIT 1
")

  CITY  WEATHER VISIBILITY TEMP  TEMP_MIN TEMP_MAX PRESSURE HUMIDITY WIND_SPEED
1 Seoul Clear   10000      12.32 10.91    12.32    1015     50       2.18
  WIND_DEG SEASON FORECAST_DATETIME
1 248      Spring 2021-04-16 12:00:00

## Task 4 - Seasons
#### Find which seasons are included in the seoul bike sharing dataset.

### Solution 4

In [7]:
# provide your solution here
dbGetQuery(conn, "
    SELECT DISTINCT SEASONS 
    FROM SEOUL_BIKE_SHARING
")

  SEASONS
1 Winter
2 Spring
3 Summer
4 Autumn

## Task 5 - Date Range
#### Find the first and last dates in the Seoul Bike Sharing dataset.

### Solution 5

In [8]:
# provide your solution here
dbGetQuery(conn, "
    SELECT MIN(DATE) AS FIRST_DATE, MAX(DATE) AS LAST_DATE 
    FROM SEOUL_BIKE_SHARING
")

  FIRST_DATE LAST_DATE
1 01/01/2018 31/12/2017

## Task 6 - Subquery - 'all-time high'
#### determine which date and hour had the most bike rentals.

### Solution 6

In [9]:
# provide your solution here
dbGetQuery(conn, "
    SELECT DATE, HOUR, RENTED_BIKE_COUNT 
    FROM SEOUL_BIKE_SHARING 
    WHERE RENTED_BIKE_COUNT = (
        SELECT MAX(RENTED_BIKE_COUNT) 
        FROM SEOUL_BIKE_SHARING
    )
")

  DATE       HOUR RENTED_BIKE_COUNT
1 19/06/2018 18   3556

## Task 7 - Hourly popularity and temperature by season
#### Determine the average hourly temperature and the average number of bike rentals per hour over each season. List the top ten results by average bike count.

### Solution 7

In [10]:
# provide your solution here
dbGetQuery(conn, "
    SELECT SEASONS, HOUR, 
           AVG(TEMPERATURE) AS AVG_TEMP, 
           AVG(RENTED_BIKE_COUNT) AS AVG_BIKES 
    FROM SEOUL_BIKE_SHARING 
    GROUP BY SEASONS, HOUR 
    ORDER BY AVG_BIKES DESC 
    LIMIT 10
")

   SEASONS HOUR AVG_TEMP AVG_BIKES
1  Summer  18   29.38791 2135.141
2  Autumn  18   16.03185 1983.333
3  Summer  19   28.27378 1889.250
4  Summer  20   27.06630 1801.924
5  Summer  21   26.27826 1754.065
6  Spring  18   15.97222 1689.311
7  Summer  22   25.69891 1567.870
8  Autumn  17   17.27778 1562.877
9  Summer  17   30.07691 1526.293
10 Autumn  19   15.06346 1515.568

## Task 8 - Rental Seasonality
#### Find the average hourly bike count during each season. 
Also include the minimum, maximum, and standard deviation of the hourly bike count for each season. 

> Hint : Use the SQRT(AVG(col*col) - AVG(col)*AVG(col) ) function where col refers to your column name for finding the standard deviation

### Solution 8

In [11]:
# provide your solution here
dbGetQuery(conn, "
    SELECT SEASONS, 
           AVG(RENTED_BIKE_COUNT) AS AVG_BIKES, 
           MIN(RENTED_BIKE_COUNT) AS MIN_BIKES, 
           MAX(RENTED_BIKE_COUNT) AS MAX_BIKES, 
           SQRT(AVG(RENTED_BIKE_COUNT * RENTED_BIKE_COUNT) - AVG(RENTED_BIKE_COUNT) * AVG(RENTED_BIKE_COUNT)) AS STD_DEV_BIKES 
    FROM SEOUL_BIKE_SHARING 
    GROUP BY SEASONS
")

  SEASONS AVG_BIKES MIN_BIKES MAX_BIKES STD_DEV_BIKES
1 Autumn   924.1105 2         3298      617.3885
2 Spring   746.2542 2         3251      618.5247
3 Summer  1034.0734 9         3556      690.0884
4 Winter   225.5412 3          937      150.3374

Let's explore a bit and see what might be the most significant contributing factors in terms of the provided data.

## Task 9 - Weather Seasonality
#### Consider the weather over each season. On average, what were the TEMPERATURE, HUMIDITY, WIND_SPEED, VISIBILITY, DEW_POINT_TEMPERATURE, SOLAR_RADIATION, RAINFALL, and SNOWFALL per season?
Include the average bike count as well , and rank the results by average bike count so you can see if it is correlated with the weather at all.

### Solution 9

In [12]:
# provide your solution here
dbGetQuery(conn, "
    SELECT SEASONS, 
           AVG(TEMPERATURE) AS AVG_TEMP, 
           AVG(HUMIDITY) AS AVG_HUMIDITY, 
           AVG(WIND_SPEED) AS AVG_WIND, 
           AVG(VISIBILITY) AS AVG_VISIBILITY, 
           AVG(DEW_POINT_TEMPERATURE) AS AVG_DEW_POINT, 
           AVG(SOLAR_RADIATION) AS AVG_SOLAR, 
           AVG(RAINFALL) AS AVG_RAIN, 
           AVG(SNOWFALL) AS AVG_SNOW, 
           AVG(RENTED_BIKE_COUNT) AS AVG_BIKES 
    FROM SEOUL_BIKE_SHARING 
    GROUP BY SEASONS 
    ORDER BY AVG_BIKES DESC
")

  SEASONS AVG_TEMP  AVG_HUMIDITY AVG_WIND AVG_VISIBILITY AVG_DEW_POINT
1 Summer  26.587711 64.98143     1.609420 1501.745        18.750136
2 Autumn  13.821580 59.04491     1.492101 1558.174         5.150594
3 Spring  13.021685 58.75833     1.857778 1240.912         4.091389
4 Winter  -2.540463 49.74491     1.922685 1445.987       -12.416667
  AVG_SOLAR AVG_RAIN   AVG_SNOW   AVG_BIKES
1 0.7612545 0.25348732 0.00000000 1034.0734
2 0.5227827 0.11765617 0.06350026  924.1105
3 0.6803009 0.18694444 0.00000000  746.2542
4 0.2981806 0.03282407 0.24750000  225.5412

## Task 10 - Total Bike Count and City Info for Seoul
#### Use an implicit join across the WORLD_CITIES and the BIKE_SHARING_SYSTEMS tables to determine the total number of bikes avaialble in Seoul, plus the following city information about Seoul: CITY, COUNTRY, LAT, LON, POPULATION, in a single view.
Notice that in this case, the CITY column will work for the WORLD_CITIES table, but in general you would have to use the CITY_ASCII column.

### Solution 10

In [13]:
# provide your solution here
dbGetQuery(conn, "
    SELECT W.CITY, W.COUNTRY, W.LAT, W.LNG, W.POPULATION, B.BICYCLES 
    FROM WORLD_CITIES W, BIKE_SHARING_SYSTEMS B 
    WHERE W.CITY = B.CITY 
      AND W.CITY = 'Seoul'
")

  CITY  COUNTRY      LAT     LNG POPULATION BICYCLES
1 Seoul Korea, South 37.5833 127 21794000   20000

## Task 11 - Find all city names and coordinates with comparable bike scale to Seoul's bike sharing system
#### Find all cities with total bike counts between 15000 and 20000. Return the city and country names, plus the coordinates (LAT, LNG), population, and number of bicycles for each city.
Later we will ask you to visualize these similar cities on leaflet, with some weather data.

### Solution 11

In [14]:
# provide your solution here
dbGetQuery(conn, "
    SELECT W.CITY, W.COUNTRY, W.LAT, W.LNG, W.POPULATION, B.BICYCLES 
    FROM WORLD_CITIES W, BIKE_SHARING_SYSTEMS B 
    WHERE W.CITY = B.CITY 
      AND B.BICYCLES BETWEEN 15000 AND 20000
")

  CITY     COUNTRY      LAT     LNG      POPULATION BICYCLES
1 Beijing  China        39.9050 116.3914 19433000   16000
2 Ningbo   China        29.8750 121.5492  7639000   15000
3 Shanghai China        31.1667 121.4667 22120000   19165
4 Weifang  China        36.7167 119.1000  9373000   20000
5 Zhuzhou  China        27.8407 113.1469  3855609   20000
6 Seoul    Korea, South 37.5833 127.0000 21794000   20000

In [16]:
dbDisconnect(conn)

## Author(s)

<h4> Jeff Grossman </h4>
<h4> Lakshmi Holla </h4>


## Other Contributor(s)

<h4>  Malika Singla </h4>

<!--## Change log

| Date (YYYY-MM-DD) | Version | Changed By | Change Description                 |
| ----------------- | ------- | ---------- | ---------------------------------- |
| 2022-03-03        | 1.0     |Lakshmi Holla  | Created lab using sqlite3          |-->

## <h3 align="center"> © IBM Corporation 2022. All rights reserved. <h3/>